/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.SPA.MantenimientoContrato;
import View.SPA.MantenimientoInquilino;
import View.SPA.MantenimientoPropietario;
import View.SPA.MantenimientoVivienda;

/**
 *
 * @author Loro
 */
public class SpanishMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SpanishMenu.class.getName());

    /**
     * Creates new form Spanish
     */
    public SpanishMenu() {
        initComponents();
        setLocationRelativeTo(null);//center in the screen
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel2 = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        Salir = new javax.swing.JButton();
        Contratos = new javax.swing.JButton();
        Inquilinos = new javax.swing.JButton();
        Viviendas = new javax.swing.JButton();
        Propietario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setText("Alquilaria s.l. All rights reserved ©");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelMenu.setBackground(new java.awt.Color(253, 253, 201));
        PanelMenu.setPreferredSize(new java.awt.Dimension(1024, 720));
        PanelMenu.setRequestFocusEnabled(false);

        Salir.setBackground(new java.awt.Color(123, 123, 36));
        Salir.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        Salir.setText("Salir del programa"); // NOI18N
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Contratos.setBackground(new java.awt.Color(219, 213, 141));
        Contratos.setFont(new java.awt.Font("Futura", 0, 36)); // NOI18N
        Contratos.setForeground(new java.awt.Color(58, 55, 36));
        Contratos.setText("Mantemimiento Contratos");
        Contratos.setToolTipText("");
        Contratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContratosActionPerformed(evt);
            }
        });

        Inquilinos.setBackground(new java.awt.Color(219, 213, 141));
        Inquilinos.setFont(new java.awt.Font("Futura", 0, 36)); // NOI18N
        Inquilinos.setForeground(new java.awt.Color(58, 55, 36));
        Inquilinos.setText("Mantenimiento Inquilinos");
        Inquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InquilinosActionPerformed(evt);
            }
        });

        Viviendas.setBackground(new java.awt.Color(219, 213, 141));
        Viviendas.setFont(new java.awt.Font("Futura", 0, 36)); // NOI18N
        Viviendas.setForeground(new java.awt.Color(58, 55, 36));
        Viviendas.setText("Mantenimiento Viviendas");
        Viviendas.setToolTipText("");
        Viviendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViviendasActionPerformed(evt);
            }
        });

        Propietario.setBackground(new java.awt.Color(219, 213, 141));
        Propietario.setFont(new java.awt.Font("Futura", 0, 36)); // NOI18N
        Propietario.setForeground(new java.awt.Color(58, 55, 36));
        Propietario.setText("Mantenimiento Propietario");
        Propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PropietarioActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("Alquilaria S.L. All rights reserved ©");

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Viviendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Propietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Inquilinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Contratos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(485, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Viviendas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Inquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Contratos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void ContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContratosActionPerformed
        // TODO add your handling code here:
        new MantenimientoContrato().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ContratosActionPerformed

    private void InquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InquilinosActionPerformed
        // TODO add your handling code here:
        new MantenimientoInquilino().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InquilinosActionPerformed

    private void ViviendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViviendasActionPerformed
        // TODO add your handling code here:
        new MantenimientoVivienda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViviendasActionPerformed

    private void PropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PropietarioActionPerformed
        // TODO add your handling code here:
        //botón propietario
        new MantenimientoPropietario().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_PropietarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SpanishMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Contratos;
    private javax.swing.JButton Inquilinos;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JButton Propietario;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Viviendas;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
