/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.SPA;

import View.*;
import View.SPA.Propietario.*;
import java.sql.ResultSet;

/**
 *
 * @author Loro
 */
public class MantenimientoPropietario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientoPropietario.class.getName());

    /**
     * Creates new form Spanish
     */
    public MantenimientoPropietario() {
        initComponents();
        setLocationRelativeTo(null);//center in the screen
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelChooseLanguage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Atrasbutton = new javax.swing.JButton();
        jLabelChooseLanguage1 = new javax.swing.JLabel();
        BorrarPropietario = new javax.swing.JButton();
        ModificarPropietario = new javax.swing.JButton();
        ConnsultarPropietario = new javax.swing.JButton();
        AddPropietario = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabelChooseLanguage.setFont(new java.awt.Font("Futura", 0, 48)); // NOI18N
        jLabelChooseLanguage.setForeground(new java.awt.Color(51, 0, 0));
        jLabelChooseLanguage.setText("Choose a Language");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 254, 224));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));

        Atrasbutton.setBackground(new java.awt.Color(107, 137, 107));
        Atrasbutton.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        Atrasbutton.setForeground(new java.awt.Color(255, 255, 255));
        Atrasbutton.setText("Atrás"); // NOI18N
        Atrasbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasbuttonActionPerformed(evt);
            }
        });

        jLabelChooseLanguage1.setFont(new java.awt.Font("Futura", 0, 48)); // NOI18N
        jLabelChooseLanguage1.setForeground(new java.awt.Color(51, 0, 0));
        jLabelChooseLanguage1.setText("Mantenimiento Propietario");

        BorrarPropietario.setBackground(new java.awt.Color(174, 202, 174));
        BorrarPropietario.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        BorrarPropietario.setForeground(new java.awt.Color(0, 51, 51));
        BorrarPropietario.setText("Borrar propietario"); // NOI18N
        BorrarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarPropietarioActionPerformed(evt);
            }
        });

        ModificarPropietario.setBackground(new java.awt.Color(174, 202, 174));
        ModificarPropietario.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        ModificarPropietario.setForeground(new java.awt.Color(0, 51, 51));
        ModificarPropietario.setText("Modificar propietario"); // NOI18N
        ModificarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarPropietarioActionPerformed(evt);
            }
        });

        ConnsultarPropietario.setBackground(new java.awt.Color(174, 202, 174));
        ConnsultarPropietario.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        ConnsultarPropietario.setForeground(new java.awt.Color(0, 51, 51));
        ConnsultarPropietario.setText("Consultar propietario"); // NOI18N
        ConnsultarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnsultarPropietarioActionPerformed(evt);
            }
        });

        AddPropietario.setBackground(new java.awt.Color(174, 202, 174));
        AddPropietario.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        AddPropietario.setForeground(new java.awt.Color(0, 51, 51));
        AddPropietario.setText("Añadir propietario"); // NOI18N
        AddPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPropietarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 797, Short.MAX_VALUE)
                .addComponent(Atrasbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BorrarPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                    .addComponent(ModificarPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConnsultarPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddPropietario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelChooseLanguage1)
                .addGap(222, 222, 222))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelChooseLanguage1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(AddPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BorrarPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConnsultarPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModificarPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(Atrasbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasbuttonActionPerformed
        // TODO add your handling code here:
        // botón atrás
        new SpanishMenu().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_AtrasbuttonActionPerformed

    private void BorrarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarPropietarioActionPerformed
        // TODO add your handling code here:
        new deletePropietario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BorrarPropietarioActionPerformed

    private void ModificarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarPropietarioActionPerformed
        // TODO add your handling code here:
        new modifyPropietario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ModificarPropietarioActionPerformed

    private void ConnsultarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnsultarPropietarioActionPerformed
        // TODO add your handling code here:
        new consultarPropietario().setVisible(true);
        this.dispose();

        
        
    }//GEN-LAST:event_ConnsultarPropietarioActionPerformed

    private void AddPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPropietarioActionPerformed
        // TODO add your handling code here:
        new AddPropietario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddPropietarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MantenimientoPropietario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPropietario;
    private javax.swing.JButton Atrasbutton;
    private javax.swing.JButton BorrarPropietario;
    private javax.swing.JButton ConnsultarPropietario;
    private javax.swing.JButton ModificarPropietario;
    private javax.swing.JLabel jLabelChooseLanguage;
    private javax.swing.JLabel jLabelChooseLanguage1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
