/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.SPA.Vivienda;

import Model.OperacionesHouse;
import View.SPA.Propietario.*;
import View.SPA.*;
import View.*;
import javax.swing.JOptionPane;
import Model.OperacionesOwner;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Loro
 */
public class consultarVivienda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(consultarVivienda.class.getName());

    /**
     * Creates new form Spanish
     */
    public consultarVivienda() {
        initComponents();
        setLocationRelativeTo(null);//center in the screen
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelChooseLanguage = new javax.swing.JLabel();
        DniField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DniField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        jLabelChooseLanguage1 = new javax.swing.JLabel();
        codeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CheckButton = new javax.swing.JButton();
        CheckAllButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabelChooseLanguage.setFont(new java.awt.Font("Futura", 0, 48)); // NOI18N
        jLabelChooseLanguage.setForeground(new java.awt.Color(51, 0, 0));
        jLabelChooseLanguage.setText("Choose a Language");

        DniField2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        DniField2.setText("jTextField1");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("DNI");

        DniField4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        DniField4.setText("jTextField1");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("DNI");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 208, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));

        Atras.setBackground(new java.awt.Color(137, 111, 181));
        Atras.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atrás"); // NOI18N
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        jLabelChooseLanguage1.setFont(new java.awt.Font("Futura", 0, 48)); // NOI18N
        jLabelChooseLanguage1.setForeground(new java.awt.Color(51, 0, 0));
        jLabelChooseLanguage1.setText("Consultar Vivienda");

        codeField.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Caladea", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("Código");

        CheckButton.setBackground(new java.awt.Color(203, 176, 249));
        CheckButton.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        CheckButton.setForeground(new java.awt.Color(61, 52, 76));
        CheckButton.setText("Consultar");
        CheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButtonActionPerformed(evt);
            }
        });

        CheckAllButton.setBackground(new java.awt.Color(203, 176, 249));
        CheckAllButton.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        CheckAllButton.setForeground(new java.awt.Color(61, 52, 76));
        CheckAllButton.setText("Consultar Todas");
        CheckAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAllButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(CheckAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelChooseLanguage1)
                        .addGap(125, 125, 125))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelChooseLanguage1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(86, 86, 86)
                .addComponent(CheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        // TODO add your handling code here:
        // botón atrás
        new MantenimientoVivienda().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_AtrasActionPerformed

    private void CheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckButtonActionPerformed
        // TODO add your handling code here:
        try {

            if (codeField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Rellene el campo id con un número", "Info", JOptionPane.INFORMATION_MESSAGE);// añadiendo "Information", JOptionPane.ERROR_MESSAGE al final cambia el icono a "I"
            } else {

                try {

                    String s = codeField.getText();
                    ResultSet rs = OperacionesHouse.showHouse(s);

                    int existe = 0;

                    String[] columnas = { "CÓDIGO", "DIRECCIÓN", "PRECIO ALQUILER", "M2", "DESCRIPCIÓN", "PERMITE MASCOTAS", "TIPO DE CASA", "ID OWNER"};
                    DefaultTableModel model = new DefaultTableModel(columnas, 0);

                    while (rs.next()) {

                        String address = rs.getString("address");
                        int rent = rs.getInt("rent");
                        int surface = rs.getInt("surface");
                        String description = rs.getString("description");
                        boolean allowsPets = rs.getBoolean("allowsPets");
                        String code = rs.getString("code");
                        int housetyp = rs.getInt("housetyp");
                        int idowner = rs.getInt("id_owner");

                        String housetype = OperacionesHouse.getHouseType(housetyp, 2);// this way se can obtain the string of the type of house, because the translations are in a mysql table, and you can choose the language,
                        // 1 for english, 2 for spanish

                        Object[] fila = {code, address, rent, surface, description, allowsPets, housetype, idowner};
                        model.addRow(fila);

                        existe++;
                    }

                    if (existe == 0) {
                        JOptionPane.showMessageDialog(this, "No se encontraron Casas con ese código", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JTable tabla = new JTable(model);
                        JScrollPane scroll = new JScrollPane(tabla);

                        // Crear ventana emergente con la tabla
                        JDialog dialogo = new JDialog(this, "Casas encontradas", true);
                        dialogo.getContentPane().add(scroll);
                        dialogo.setSize(600, 300);
                        dialogo.setLocationRelativeTo(this); // Centrar respecto a la ventana principal
                        dialogo.setVisible(true);
                    }

                } catch (SQLException sb) {
                    JOptionPane.showMessageDialog(this, "Error con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Rellene el campo con un código alfanumérico válido", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_CheckButtonActionPerformed

    private void CheckAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAllButtonActionPerformed
        // TODO add your handling code here:

        try {

            ResultSet rs = OperacionesHouse.showAllHouses();

            int existe = 0;

            String[] columnas = { "CÓDIGO", "DIRECCIÓN", "PRECIO ALQUILER", "M2", "DESCRIPCIÓN", "PERMITE MASCOTAS", "TIPO DE CASA", "ID OWNER"};
            DefaultTableModel model = new DefaultTableModel(columnas, 0);

            while (rs.next()) {

                String address = rs.getString("address");
                int rent = rs.getInt("rent");
                int surface = rs.getInt("surface");
                String description = rs.getString("description");
                boolean allowsPets = rs.getBoolean("allowsPets");
                String code = rs.getString("code");
                int housetyp = rs.getInt("housetyp");
                int idowner = rs.getInt("id_owner");

                String housetype = OperacionesHouse.getHouseType(housetyp,2);// this way se can obtain the string of the type of house, because the translations are in a mysql table, and you can choose the language,
                // 1 for english, 2 for spanish

                Object[] fila = { code, address, rent, surface, description, allowsPets, housetype, idowner};
                model.addRow(fila);

                existe++;
            }

            if (existe == 0) {
                JOptionPane.showMessageDialog(this, "No se encontraron Casas, cree alguna", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JTable tabla = new JTable(model);
                JScrollPane scroll = new JScrollPane(tabla);

                // Crear ventana emergente con la tabla
                JDialog dialogo = new JDialog(this, "Casas encontradas", true);
                dialogo.getContentPane().add(scroll);
                dialogo.setSize(600, 300);
                dialogo.setLocationRelativeTo(this); // Centrar respecto a la ventana principal
                dialogo.setVisible(true);
            }

        } catch (SQLException sb) {
            JOptionPane.showMessageDialog(this, "Error con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_CheckAllButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new consultarVivienda().setVisible(true));
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton CheckAllButton;
    private javax.swing.JButton CheckButton;
    private javax.swing.JTextField DniField2;
    private javax.swing.JTextField DniField4;
    private javax.swing.JTextField codeField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelChooseLanguage;
    private javax.swing.JLabel jLabelChooseLanguage1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
