/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.SPA.Propietario;

import View.SPA.*;
import View.*;
import javax.swing.JOptionPane;
import Model.OperacionesOwner;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Loro
 */
public class deletePropietario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(deletePropietario.class.getName());

    /**
     * Creates new form Spanish
     */
    public deletePropietario() {
        initComponents();
        setLocationRelativeTo(null);//center in the screen
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelChooseLanguage = new javax.swing.JLabel();
        DniField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DniField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        jLabelChooseLanguage1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BorrButton = new javax.swing.JButton();
        CheckAllOwner = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabelChooseLanguage.setFont(new java.awt.Font("Futura", 0, 48)); // NOI18N
        jLabelChooseLanguage.setForeground(new java.awt.Color(51, 0, 0));
        jLabelChooseLanguage.setText("Choose a Language");

        DniField2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        DniField2.setText("jTextField1");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("DNI");

        DniField4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        DniField4.setText("jTextField1");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("DNI");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 254, 224));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));

        Atras.setBackground(new java.awt.Color(0, 102, 51));
        Atras.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        Atras.setText("Atrás"); // NOI18N
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        jLabelChooseLanguage1.setFont(new java.awt.Font("Futura", 0, 48)); // NOI18N
        jLabelChooseLanguage1.setForeground(new java.awt.Color(51, 0, 0));
        jLabelChooseLanguage1.setText("Borrar Propietario");

        idField.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Caladea", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("Id");

        BorrButton.setBackground(new java.awt.Color(174, 202, 174));
        BorrButton.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        BorrButton.setForeground(new java.awt.Color(0, 51, 51));
        BorrButton.setText("Borrar");
        BorrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrButtonActionPerformed(evt);
            }
        });

        CheckAllOwner.setBackground(new java.awt.Color(174, 202, 174));
        CheckAllOwner.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        CheckAllOwner.setForeground(new java.awt.Color(0, 51, 51));
        CheckAllOwner.setText("Consultar Propietarios");
        CheckAllOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAllOwnerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(CheckAllOwner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BorrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelChooseLanguage1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(131, 131, 131))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelChooseLanguage1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(77, 77, 77)
                .addComponent(BorrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckAllOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        // TODO add your handling code here:
        // botón atrás
        new MantenimientoPropietario().setVisible(true); 
        this.dispose();

    }//GEN-LAST:event_AtrasActionPerformed

    private void BorrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrButtonActionPerformed
        // TODO add your handling code here:
        boolean boo = false;
        boolean isNum = false;
        int num = 0;

        if (idField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Rellene el campo id con un número", "Info", JOptionPane.INFORMATION_MESSAGE);// añadiendo "Error", JOptionPane.ERROR_MESSAGE al final cambia el icoono a error
        } else {

            try {
                num = Integer.parseInt(idField.getText());
                isNum = true;

            } catch (NumberFormatException ex) {
                isNum = false;
            }

            if (isNum) {

                try {

                    boo = OperacionesOwner.borrPropietario(num);

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error al borrar el propietario", "Error", JOptionPane.ERROR_MESSAGE);
                }

                if (boo) {
                    JOptionPane.showMessageDialog(this, "El propietario se ha borrado satisfactoriamente","Info", JOptionPane.INFORMATION_MESSAGE);
                    idField.setText("");

                } else {
                    JOptionPane.showMessageDialog(this, "Error al borrar al propietario", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }else{
                JOptionPane.showMessageDialog(this, "Error, el campo id debe de ser únicamente un número", "Error", JOptionPane.ERROR_MESSAGE);
            
            }

        }
    }//GEN-LAST:event_BorrButtonActionPerformed

    private void CheckAllOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAllOwnerActionPerformed
        // TODO add your handling code here:
         try {

                    ResultSet rs = OperacionesOwner.showAllOwners();

                    int existe = 0;

                    String[] columnas = {"ID", "DNI", "Nombre", "Email", "Teléfono"};
                    DefaultTableModel model = new DefaultTableModel(columnas, 0);
                    
                    while (rs.next()) {
             

                        int id = rs.getInt("id");
                        String dni = rs.getString("dni");
                        String nombre = rs.getString("name");
                        String email = rs.getString("email");
                        String telefono = rs.getString("phonenumber");

                        Object[] fila = {id, dni, nombre, email, telefono};
                        model.addRow(fila);

                        existe++;
                    }

                    if (existe == 0) {
                        JOptionPane.showMessageDialog(this, "No se encontraron Propietarios", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JTable tabla = new JTable(model);
                        JScrollPane scroll = new JScrollPane(tabla);

                        // Crear ventana emergente con la tabla
                        JDialog dialogo = new JDialog(this, "Propietarios", true);
                        dialogo.getContentPane().add(scroll);
                        dialogo.setSize(600, 300);
                        dialogo.setLocationRelativeTo(this); // centrar a esta ventana
                        dialogo.setVisible(true);
                    }

                } catch (SQLException sb) {
                        JOptionPane.showMessageDialog(this, "Error con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
                }        
    }//GEN-LAST:event_CheckAllOwnerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new deletePropietario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton BorrButton;
    private javax.swing.JButton CheckAllOwner;
    private javax.swing.JTextField DniField2;
    private javax.swing.JTextField DniField4;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelChooseLanguage;
    private javax.swing.JLabel jLabelChooseLanguage1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
