/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.SPA.Inquilino;

import View.SPA.Propietario.*;
import View.SPA.*;
import View.*;
import javax.swing.JOptionPane;
import Model.OperacionesTenant;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Loro
 */
public class modifyTenant extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(modifyTenant.class.getName());

    /**
     * Creates new form Spanish
     */
    public modifyTenant() {
        initComponents();
        setLocationRelativeTo(null);//center in the screen
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelChooseLanguage = new javax.swing.JLabel();
        DniField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DniField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        jLabelChooseLanguage1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ModifyButton = new javax.swing.JButton();
        checkByIdButton = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        DniField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        checkAllTenantsButton = new javax.swing.JButton();
        hasPetsComboBox = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabelChooseLanguage.setFont(new java.awt.Font("Futura", 0, 48)); // NOI18N
        jLabelChooseLanguage.setForeground(new java.awt.Color(51, 0, 0));
        jLabelChooseLanguage.setText("Choose a Language");

        DniField2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        DniField2.setText("jTextField1");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("DNI");

        DniField4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        DniField4.setText("jTextField1");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("DNI");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 175, 175));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));

        Atras.setBackground(new java.awt.Color(163, 109, 109));
        Atras.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atrás"); // NOI18N
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        jLabelChooseLanguage1.setFont(new java.awt.Font("Futura", 0, 48)); // NOI18N
        jLabelChooseLanguage1.setForeground(new java.awt.Color(51, 0, 0));
        jLabelChooseLanguage1.setText("Modificar Inqulino");

        idField.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Caladea", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("Id");

        ModifyButton.setBackground(new java.awt.Color(230, 153, 153));
        ModifyButton.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        ModifyButton.setForeground(new java.awt.Color(51, 0, 16));
        ModifyButton.setText("Modificar");
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });

        checkByIdButton.setBackground(new java.awt.Color(230, 153, 153));
        checkByIdButton.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        checkByIdButton.setForeground(new java.awt.Color(51, 0, 16));
        checkByIdButton.setText("Consultar \nEsa ID");
        checkByIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkByIdButtonActionPerformed(evt);
            }
        });

        NameField.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N

        DniField.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Caladea", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setText("DNI");

        jLabel5.setFont(new java.awt.Font("Caladea", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Caladea", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jLabel7.setText("Teléfono");

        phoneField.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N

        emailField.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Caladea", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 0));
        jLabel8.setText("Email");

        checkAllTenantsButton.setBackground(new java.awt.Color(230, 153, 153));
        checkAllTenantsButton.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        checkAllTenantsButton.setForeground(new java.awt.Color(51, 0, 16));
        checkAllTenantsButton.setText("Consultar  Inquilinos");
        checkAllTenantsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAllTenantsButtonActionPerformed(evt);
            }
        });

        hasPetsComboBox.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        hasPetsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiene Mascotas", "No tiene Mascotas" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(checkByIdButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(checkAllTenantsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DniField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasPetsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelChooseLanguage1)
                        .addGap(134, 134, 134))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelChooseLanguage1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addComponent(hasPetsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ModifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAllTenantsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkByIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        // TODO add your handling code here:
        // botón atrás
        new MantenimientoInquilino().setVisible(true); 
        this.dispose();

    }//GEN-LAST:event_AtrasActionPerformed

    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
        // TODO add your handling code here:
        boolean isNum;
        int num = 0;

        try {

            if (idField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Rellene el campo id con un número", "Info", JOptionPane.INFORMATION_MESSAGE);// añadiendo "Error", JOptionPane.ERROR_MESSAGE al final cambia el icoono a error
            } else {

                num = Integer.parseInt(idField.getText());
                isNum = true;


                if (isNum = true) {
                    String s = idField.getText();
                    num = Integer.parseInt(idField.getText());

                    try {
                        String seleccionMascotas = (String) hasPetsComboBox.getSelectedItem();
                        boolean hasPets = seleccionMascotas.equals("Tiene Mascotas");                        
                        boolean boo = OperacionesTenant.modifyTenant(num, DniField.getText(), NameField.getText(), phoneField.getText(), emailField.getText(), hasPets);

                        if (boo) {
                            JOptionPane.showMessageDialog(this, "El inquilino se ha modificado", "Info", JOptionPane.INFORMATION_MESSAGE);// añadiendo "Error", JOptionPane.ERROR_MESSAGE al final cambia el icoono a error
                        } else {
                            JOptionPane.showMessageDialog(this, "Por algún motivo el inquilino no se ha modificado", "Info", JOptionPane.INFORMATION_MESSAGE);// añadiendo "Error", JOptionPane.ERROR_MESSAGE al final cambia el icoono a error
                        }

                    } catch (SQLException ex) {
                        Logger.getLogger(modifyTenant.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Rellene el campo id con un número", "Info", JOptionPane.INFORMATION_MESSAGE);// añadiendo "Error", JOptionPane.ERROR_MESSAGE al final cambia el icoono a error
                }

            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Rellene el campo id con un número positivo", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ModifyButtonActionPerformed

    private void checkByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkByIdButtonActionPerformed
        // TODO add your handling code here:
        boolean isNum = false;
        int num = 0;
        
        try {
            

        if (idField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Rellene el campo id con un número", "Info", JOptionPane.INFORMATION_MESSAGE);// añadiendo "Information", JOptionPane.ERROR_MESSAGE al final cambia el icono a "I"
        } else {
            
            String s = idField.getText();
            Integer.parseInt(s);
            isNum = true;


            if (isNum = true) {
                try {

                    String sb = idField.getText();
                    num = Integer.parseInt(idField.getText());
                    ResultSet rs = OperacionesTenant.showTenant(num);

                    int existe = 0;

                    String[] columnas = {"ID", "DNI", "Nombre", "Email", "Teléfono", "Tiene Mascotas"};
                    DefaultTableModel model = new DefaultTableModel(columnas, 0);

                    while (rs.next()) {

                        int id = rs.getInt("id");
                        String dni = rs.getString("dni");
                        String nombre = rs.getString("name");
                        String email = rs.getString("email");
                        String telefono = rs.getString("phonenumber");
                        boolean hasPets = rs.getBoolean("haspets");

                        Object[] fila = {id, dni, nombre, email, telefono, hasPets};
                        model.addRow(fila);

                        existe++;
                    }

                    if (existe == 0) {
                        JOptionPane.showMessageDialog(this, "No se encontraron Inquilinos con ese id", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JTable tabla = new JTable(model);
                        JScrollPane scroll = new JScrollPane(tabla);

                        // Crear ventana emergente con la tabla
                        JDialog dialogo = new JDialog(this, "Inqulinos encontrados", true);
                        dialogo.getContentPane().add(scroll);
                        dialogo.setSize(600, 300);
                        dialogo.setLocationRelativeTo(this); // Centrar respecto a la ventana principal
                        dialogo.setVisible(true);
                    }

                } catch (SQLException sb) {
                        JOptionPane.showMessageDialog(this, "Error con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }else{
                JOptionPane.showMessageDialog(this, "Rellene el campo id con un número positivo", "Error", JOptionPane.ERROR_MESSAGE);
            
            }

        }
            

        } catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(this, "Rellene el campo id con un número positivo", "Error", JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_checkByIdButtonActionPerformed

    private void checkAllTenantsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAllTenantsButtonActionPerformed
        // TODO add your handling code here:
        try {

            ResultSet rs = OperacionesTenant.showAllTenants();

            int existe = 0;

            String[] columnas = {"ID", "DNI", "Nombre", "Email", "Teléfono", "Tiene Mascotas"};
            DefaultTableModel model = new DefaultTableModel(columnas, 0);

            while (rs.next()) {

                int id = rs.getInt("id");
                String dni = rs.getString("dni");
                String nombre = rs.getString("name");
                String email = rs.getString("email");
                String telefono = rs.getString("phonenumber");
                boolean hasPets = rs.getBoolean("haspets");

                Object[] fila = {id, dni, nombre, email, telefono, hasPets};
                model.addRow(fila);

                existe++;
            }

            if (existe == 0) {
                JOptionPane.showMessageDialog(this, "No se encontraron Inquilinos", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JTable tabla = new JTable(model);
                JScrollPane scroll = new JScrollPane(tabla);

                // Crear ventana emergente con la tabla
                JDialog dialogo = new JDialog(this, "Inquilinos", true);
                dialogo.getContentPane().add(scroll);
                dialogo.setSize(600, 300);
                dialogo.setLocationRelativeTo(this); // centrar a esta ventana
                dialogo.setVisible(true);
            }

        } catch (SQLException sb) {
            JOptionPane.showMessageDialog(this, "Error con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_checkAllTenantsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new modifyTenant().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JTextField DniField;
    private javax.swing.JTextField DniField2;
    private javax.swing.JTextField DniField4;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton checkAllTenantsButton;
    private javax.swing.JButton checkByIdButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JComboBox<String> hasPetsComboBox;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelChooseLanguage;
    private javax.swing.JLabel jLabelChooseLanguage1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField phoneField;
    // End of variables declaration//GEN-END:variables
}
